name: Agent Activity Notifications

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened, labeled]

jobs:
  notify-agent-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check for Agent Commits
        id: check-commits
        run: |
          if git log -1 --pretty=%B | grep -q "\[AGENT\]"; then
            echo "Agent activity detected"
            echo "agent_active=true" >> $GITHUB_OUTPUT
          else
            echo "agent_active=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Parse Agent Type
        id: parse-agent
        if: steps.check-commits.outputs.agent_active == 'true'
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ $COMMIT_MSG == *"[FRONTEND]"* ]]; then
            echo "agent_type=Frontend Engineer" >> $GITHUB_OUTPUT
          elif [[ $COMMIT_MSG == *"[BACKEND]"* ]]; then
            echo "agent_type=Backend Engineer" >> $GITHUB_OUTPUT
          elif [[ $COMMIT_MSG == *"[TEST]"* ]]; then
            echo "agent_type=Testing Expert" >> $GITHUB_OUTPUT
          elif [[ $COMMIT_MSG == *"[SECURITY]"* ]]; then
            echo "agent_type=Cybersecurity Expert" >> $GITHUB_OUTPUT
          else
            echo "agent_type=Unknown" >> $GITHUB_OUTPUT
          fi
      
      - name: Update Activity Log
        if: steps.check-commits.outputs.agent_active == 'true'
        run: |
          mkdir -p agents
          echo "[$(date -u +"%Y-%m-%d %H:%M:%S UTC")] [${{ steps.parse-agent.outputs.agent_type || 'Unknown' }}] [ACTIVE] ${{ github.event.head_commit.message }}" >> agents/activity-log.md
      
      - name: Create Summary
        if: steps.check-commits.outputs.agent_active == 'true'
        run: |
          echo "## 🤖 Agent Activity Detected" >> $GITHUB_STEP_SUMMARY
          echo "**Agent**: ${{ steps.parse-agent.outputs.agent_type || 'Unknown' }}" >> $GITHUB_STEP_SUMMARY
          echo "**Activity**: ${{ github.event.head_commit.message }}" >> $GITHUB_STEP_SUMMARY
          echo "**Time**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_STEP_SUMMARY